apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
    name: service-with-docs
    description: a documentation service
    annotations:
        backstage.io/techdocs-ref: dir:.
spec:
    type: service
    lifecycle: production
    owner: idpadmins
    system: project-x
