apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: '{{ user.name }}'
spec:
  profile:
    displayName: '{{ user.name }}'
    email: '{{ user.email }}'
  memberOf: [finaqua-group, employees]